### ISSUE TITLE
A  problem about blurpool

### ISSUE THREAD

**Issue by linleoxdu** [mxtsai/ELNet#2]
Thanks for your code, it really helps me a lot. In paper _Making Convolutional Networks Shift-Invariant Again_, maxpool is divided into two steps: densely max-pooled and blurpool. However, in your implementation of blurpool, I find that the first one(max-pooled)  is left out. I wonder if this implementation can improve the accuracy and why.

**Comment by mxtsai** [comment]
Hi! You're correct that we left out Max-Pool in our ELNet implementation. Instead, we directly applied BlurPool with a stride of 2 to obtain a downsampled feature representation. If I remembered correctly (since this work was done a little over two years ago), we tried both implementations (single stride max-pooling followed by BlurPool and direct stride 2 BlurPool) and we didn't observe any noticeable difference in their performances. However, we were able to train our model faster with two stride BlurPool so we stuck with that implementation. Please let me know if any more clarification is needed. Thanks!

**Comment by linleoxdu** [comment]
I get it. Thanks for your answer again!

**Comment by mxtsai** [comment]
Glad it helped :)
